Authentication added
MaxxLiss/kotlin-project-marketplace pull request #3
Opened 2024-10-07 16:40 UTC by MaxxLiss

This feature contains authentication:
1. UserDetails is a data class that stores authentication information about each user
2. UserDetailsRepository is an interface that creates requests to DB about UserDetails
3. AuthService and AuthServiceImpl are contain authentication buisness logic 
4. AuthControler is a class receives HTTP authentication requests 
Also realized some dto classes and exceptions.

Authentication includes integration tests, AuthService also includes unit tests.

2024-10-07 17:40 UTC, Kokorev-VD commented on .gitignore
> +src/main/resources/sql/test_sql.sql
Не стоило, если правильно понимаю, то это будет использоваться в тестах -> без этого файлика тесты будут неполноценны

2024-10-07 18:00 UTC, Kokorev-VD requested changes

2024-10-07 18:00 UTC, Kokorev-VD commented on src/main/kotlin/org/example/kotlinprojectmarketplace/controller/AuthController.kt
> +    fun register(@RequestBody authRequest: AuthRequest): ResponseEntity<String> {
1) В Kotlin ты можешь использовать try как оператор -> надо стремиться к коду вида
`fun some() = try{//someCode}catch(){//someCode}`
2) Обработчик ошибок по-хорошему делается по другому, на это будет отдельная задача

2024-10-07 18:00 UTC, Kokorev-VD commented on src/main/kotlin/org/example/kotlinprojectmarketplace/controller/AuthController.kt
> +    // todo нормальный Response. Возможно, надо переработать AuthResponse
Да, сделай AuthResponse. В будущем он будет доработан

2024-10-07 18:00 UTC, Kokorev-VD commented on src/main/kotlin/org/example/kotlinprojectmarketplace/database/dto/auth/AuthResponse.kt
> +enum class AuthResponseMessage(val text: String) {
Молодец, что использовал enum. Как один из вариантов очень хорошо

2024-10-07 18:00 UTC, Kokorev-VD commented on src/main/kotlin/org/example/kotlinprojectmarketplace/database/entity/UserDetails.kt
> +    @Column(name = "login", length = 30, nullable = false, unique = true)
Вроде по умолчанию nullable = false и unique = false

2024-10-07 18:00 UTC, Kokorev-VD commented on src/main/kotlin/org/example/kotlinprojectmarketplace/database/repository/UserDetailsRepository.kt
> +    fun findByLogin(login: String): UserDetails?
Лучше возвращать Optional<UserDetails>, а не работать с null

2024-10-07 18:00 UTC, Kokorev-VD commented on src/main/kotlin/org/example/kotlinprojectmarketplace/exception/auth/AuthException.kt
> +    override val message: String = "Smth went wrong during the authentication"
Почему не в конструкторе?
Лучше сделать sealed AppException, унаследовать его от RuntimeException и впоследствии наследоваться от него
В целом, для бизнесовых ошибок лучше наследоваться от RuntimeException тк оно в java является uncheked, а Exception -  checked -> если ты будешь интегрировать свой код с java, то придется прописывать лишние аннотации @Throws

2024-10-07 18:00 UTC, Kokorev-VD commented on src/main/kotlin/org/example/kotlinprojectmarketplace/exception/auth/DuplicateLoginException.kt
> +class DuplicateLoginException : AuthException() {
Имхо избыточно. Авторизация - не такая большая часть приложения, чтобы распиливать его исключения на столь мелкие части

2024-10-07 18:00 UTC, Kokorev-VD commented on src/main/kotlin/org/example/kotlinprojectmarketplace/exception/auth/WrongCredentialsException.kt
> +class WrongCredentialsException : AuthException() {
-//-

2024-10-07 18:00 UTC, Kokorev-VD commented on src/main/kotlin/org/example/kotlinprojectmarketplace/database/entity/UserDetails.kt
> +data class UserDetails (
Стоит добавить поле createdAt (в sql соответственно тоже)

2024-10-07 18:00 UTC, Kokorev-VD commented on src/main/kotlin/org/example/kotlinprojectmarketplace/service/AuthServiceImpl.kt
> +    @Throws(AuthException::class)
Вот как раз про что я говорил. Наследуясь от RuntimeException можно было бы забить и все работало бы

2024-10-07 18:00 UTC, Kokorev-VD commented on src/test/kotlin/org/example/kotlinprojectmarketplace/integration/AuthIntegrationTest.kt
> +class AuthIntegrationTest {
Лучше прописать AbstractIntegrationTest, куда вынести всякие настройки типо mockMvc, objectMapper'ов и тд

2024-10-07 18:00 UTC, Kokorev-VD commented on src/test/kotlin/org/example/kotlinprojectmarketplace/integration/AuthIntegrationTest.kt
> +        // возможно, получится сделать save(Any), но кажется, что можно лучше
Обычно verify() проверяет, что просто такой вызов был сделан, а уже проверка, что сохранилось именно то, что ты сохранил отдельно, как у тебя и сделано, так что норм

2024-10-07 18:00 UTC, Kokorev-VD commented on src/test/kotlin/org/example/kotlinprojectmarketplace/integration/AuthIntegrationTest.kt
> +        assertNotNull(userDetailsResult)
Стоит вынести наверх, чтобы проверить, что пользователь с таким логином действительно существует на момент запроса

2024-10-07 18:14 UTC, MaxxLiss commented on .gitignore
> +src/main/resources/sql/test_sql.sql
Нет, это я чтобы запросы писать самостоятельно, если надо будет

2024-10-07 18:23 UTC, MaxxLiss commented on src/main/kotlin/org/example/kotlinprojectmarketplace/database/entity/UserDetails.kt
> +data class UserDetails (
Может, это лучше в обычного юзера?
Тут всё-таки информация про регистрацию

2024-11-25 12:48 UTC, MaxxLiss reviewed
Authentication has been updated. The user now receives a jwt token to access other requests.
UserInfo has been added. Now user information can be enriched with some data (name, email address...). Only authenticated users can enrich information about themselves. UserInfoIntegrationTest has been also added.

2025-12-05 14:35 UTC, merged